# Generated by Django 2.1.12 on 2023-01-14 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('parkingplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.IntegerField()),
                ('updated_at', models.IntegerField()),
                ('format_created_at', models.DateTimeField(auto_now=True)),
                ('format_updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'pre'), (1, 'parking'), (2, 'paying'), (3, 'finish')])),
                ('parkingBeginTime', models.IntegerField(blank=True, default=0, null=True)),
                ('parkingPlace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parkingPlace_order', to='parkingplace.ParkingPlace')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_order', to='users.Users')),
            ],
            options={
                'verbose_name': 'Orders',
                'verbose_name_plural': 'Orders',
                'db_table': 'Orders',
            },
        ),
    ]
