# Generated by Django 2.1.12 on 2023-01-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.IntegerField()),
                ('updated_at', models.IntegerField()),
                ('format_created_at', models.DateTimeField(auto_now=True)),
                ('format_updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('hourPrice', models.FloatField()),
                ('monthPrice', models.FloatField()),
                ('d', models.IntegerField()),
                ('m', models.IntegerField()),
                ('s', models.IntegerField()),
            ],
            options={
                'verbose_name': 'ParkingLot',
                'verbose_name_plural': 'ParkingLot',
                'db_table': 'ParkingLot',
            },
        ),
    ]
