# Generated by Django 2.1.12 on 2023-01-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinglot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglot',
            name='d',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='m',
        ),
        migrations.RemoveField(
            model_name='parkinglot',
            name='s',
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
