# Generated by Django 2.1.12 on 2023-01-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='money',
            field=models.FloatField(default=0),
        ),
    ]
